remote-theme: jekyll/minima
jekyll/minima:
    skin: dark

title: ddejohn/life
description: A NumPy-oriented implementation of Conway's Game of Life with options for fixed or periodic boundary conditions.
